### ISSUE TITLE
Feature Request: Set custom FPS

### ISSUE THREAD

**Issue by binho** [numen31337/AKVideoImageView#1]

**Comment by numen31337** [comment]
Hi @binho, I am sorry for so late answer, for some reason I missed your issue.
In order to change video FPS, you need to reencode video itself, this will be a better solution and will save a disc space for you. You can do it like so for example:
`ffmpeg -i video_1.mp4 -r 5 -y output.mp4`

[Here is more precise info how to change video frame rate](http://stackoverflow.com/questions/11004137/re-sampling-h264-video-to-reduce-frame-rate-while-maintaining-high-image-quality)

Hope this will solve your issue
